DROP TABLE [dbo].[Class_Book];
DROP TABLE [dbo].[Book];
DROP TABLE [dbo].[Class];
DROP TABLE [dbo].[Student];
DROP TABLE [dbo].[Education_Subject];
DROP TABLE [dbo].[Education];
DROP TABLE [dbo].[Teacher_Subject];
DROP TABLE [dbo].[Subject];
DROP TABLE [dbo].[Teacher];



CREATE TABLE Teacher( Teacher_Id int NOT NULL PRIMARY KEY IDENTITY(1,1), Name varchar(50) NOT NULL);

CREATE TABLE Subject( Subject_Id int NOT NULL PRIMARY KEY IDENTITY(1,1), SubjectName varchar(50) NOT NULL);

CREATE TABLE Teacher_Subject( TeacherSub_Id	int NOT NULL PRIMARY KEY IDENTITY(1,1), Teacher_Id int NOT NULL, Subject_Id int NOT NULL, FOREIGN KEY (Teacher_Id) REFERENCES Teacher(Teacher_Id) ON UPDATE NO ACTION ON DELETE CASCADE, FOREIGN KEY (Subject_Id) REFERENCES Subject(Subject_Id) ON UPDATE NO ACTION ON DELETE CASCADE);

CREATE TABLE Education( Edu_Id int NOT NULL PRIMARY KEY IDENTITY(1,1), EduName varchar(50) NOT NULL);

CREATE TABLE Education_Subject( EduSub_Id int NOT NULL PRIMARY KEY IDENTITY(1,1), Edu_Id int NOT NULL, Subject_Id int NOT NULL, FOREIGN KEY (Edu_Id) REFERENCES Education(Edu_Id) ON UPDATE NO ACTION ON DELETE CASCADE, FOREIGN KEY (Subject_Id) REFERENCES Subject(Subject_Id) ON UPDATE NO ACTION ON DELETE CASCADE);

CREATE TABLE Student( Student_Id int NOT NULL PRIMARY KEY IDENTITY(1,1), StudentName varchar(50) NOT NULL, Address varchar(70) NOT NULL);

CREATE TABLE Class( Class_Id int NOT NULL PRIMARY KEY IDENTITY(1,1), ClassName varchar(50) NOT NULL, Term int NOT NULL, EduSub_Id int NOT NULL, TeacherSub_Id int NOT NULL, Student_Id int NOT NULL, FOREIGN KEY (EduSub_Id) REFERENCES Education_Subject(EduSub_Id), FOREIGN KEY (TeacherSub_Id) REFERENCES Teacher_Subject(TeacherSub_Id), FOREIGN KEY (Student_Id) REFERENCES Student(Student_Id));

CREATE TABLE Book( Book_Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), Title VARCHAR(50) NOT NULL, Author VARCHAR(50) NOT NULL, Year INT NOT NULL, ISBN INT NULL, Amount INT NULL);

CREATE TABLE Class_Book( CB_Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), Class_Id INT NOT NULL, Book_Id INT NOT NULL, FOREIGN KEY (Class_Id) REFERENCES Class(Class_Id) ON UPDATE NO ACTION ON DELETE CASCADE, FOREIGN KEY (Book_Id) REFERENCES Book(Book_Id) ON UPDATE NO ACTION ON DELETE CASCADE );
