// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Book")]
    public partial class Book
    {
        public Book()
        {
            ClassBooks = new HashSet<ClassBook>();
        }

        [Key]
        [Column("Book_Id")]
        public int BookId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Title { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Author { get; set; }
        public int Year { get; set; }
        [Column("ISBN")]
        public int? Isbn { get; set; }
        public int? Amount { get; set; }

        [InverseProperty("Book")]
        public virtual ICollection<ClassBook> ClassBooks { get; set; }
    }
}