// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Bookware.Models
{
    public partial class BookwareDBContext : DbContext
    {
        public BookwareDBContext()
        {
        }

        public BookwareDBContext(DbContextOptions<BookwareDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassBook> ClassBooks { get; set; }
        public virtual DbSet<EduSub> EduSubs { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeacherClass> TeacherClasses { get; set; }
        public virtual DbSet<TeacherEdu> TeacherEdus { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ClassBook>(entity =>
            {
                entity.HasKey(e => e.CbId)
                    .HasName("PK__Class_Bo__4A5EFCFD70828B5F");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.ClassBooks)
                    .HasForeignKey(d => d.BookId)
                    .HasConstraintName("FK__Class_Boo__Book___74444068");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.ClassBooks)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__Class_Boo__Class__73501C2F");
            });

            modelBuilder.Entity<EduSub>(entity =>
            {
                entity.HasOne(d => d.Edu)
                    .WithMany(p => p.EduSubs)
                    .HasForeignKey(d => d.EduId)
                    .HasConstraintName("FK__Edu_Sub__Edu_Id__67DE6983");

                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.EduSubs)
                    .HasForeignKey(d => d.SubjectId)
                    .HasConstraintName("FK__Edu_Sub__Subject__68D28DBC");
            });

            modelBuilder.Entity<Education>(entity =>
            {
                entity.HasKey(e => e.EduId)
                    .HasName("PK__Educatio__E5726EA24EA26D66");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasOne(d => d.Class)
                    .WithMany(p => p.Students)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Student__Class_I__6319B466");
            });

            modelBuilder.Entity<TeacherClass>(entity =>
            {
                entity.HasKey(e => e.TeachClassId)
                    .HasName("PK__Teacher___425FAFF359432EFD");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.TeacherClasses)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__Teacher_C__Class__6F7F8B4B");

                entity.HasOne(d => d.TeachEdu)
                    .WithMany(p => p.TeacherClasses)
                    .HasForeignKey(d => d.TeachEduId)
                    .HasConstraintName("FK__Teacher_C__Teach__7073AF84");
            });

            modelBuilder.Entity<TeacherEdu>(entity =>
            {
                entity.HasKey(e => e.TeachEduId)
                    .HasName("PK__Teacher___1B9FC65144628489");

                entity.HasOne(d => d.EduSub)
                    .WithMany(p => p.TeacherEdus)
                    .HasForeignKey(d => d.EduSubId)
                    .HasConstraintName("FK__Teacher_E__EduSu__6CA31EA0");

                entity.HasOne(d => d.Teacher)
                    .WithMany(p => p.TeacherEdus)
                    .HasForeignKey(d => d.TeacherId)
                    .HasConstraintName("FK__Teacher_E__Teach__6BAEFA67");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}