// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Bookware.Models
{
    public partial class BookwareDbContext : DbContext
    {
        public BookwareDbContext(DbContextOptions<BookwareDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassBook> ClassBooks { get; set; }
        public virtual DbSet<EduSub> EduSubs { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeacherClass> TeacherClasses { get; set; }
        public virtual DbSet<TeacherEdu> TeacherEdus { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ClassBook>(entity =>
            {
                entity.HasKey(e => e.CbId)
                    .HasName("PK__Class_Bo__4A5EFCFD7070A0A2");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.ClassBooks)
                    .HasForeignKey(d => d.BookId)
                    .HasConstraintName("FK__Class_Boo__Book___160F4887");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.ClassBooks)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__Class_Boo__Class__07C12930");
            });

            modelBuilder.Entity<EduSub>(entity =>
            {
                entity.HasOne(d => d.Edu)
                    .WithMany(p => p.EduSubs)
                    .HasForeignKey(d => d.EduId)
                    .HasConstraintName("FK__Edu_Sub__Edu_Id__7C4F7684");

                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.EduSubs)
                    .HasForeignKey(d => d.SubjectId)
                    .HasConstraintName("FK__Edu_Sub__Subject__7D439ABD");
            });

            modelBuilder.Entity<Education>(entity =>
            {
                entity.HasKey(e => e.EduId)
                    .HasName("PK__Educatio__E5726EA2FE5EBECE");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasOne(d => d.Class)
                    .WithMany(p => p.Students)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__Student__Class_I__3C34F16F");
            });

            modelBuilder.Entity<TeacherClass>(entity =>
            {
                entity.HasKey(e => e.TeachClassId)
                    .HasName("PK__Teacher___425FAFF35ED5C3B9");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.TeacherClasses)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__Teacher_C__Class__03F0984C");

                entity.HasOne(d => d.TeachEdu)
                    .WithMany(p => p.TeacherClasses)
                    .HasForeignKey(d => d.TeachEduId)
                    .HasConstraintName("FK__Teacher_C__Teach__04E4BC85");
            });

            modelBuilder.Entity<TeacherEdu>(entity =>
            {
                entity.HasKey(e => e.TeachEduId)
                    .HasName("PK__Teacher___1B9FC651D1D58DA2");

                entity.HasOne(d => d.EduSub)
                    .WithMany(p => p.TeacherEdus)
                    .HasForeignKey(d => d.EduSubId)
                    .HasConstraintName("FK__Teacher_E__EduSu__01142BA1");

                entity.HasOne(d => d.Teacher)
                    .WithMany(p => p.TeacherEdus)
                    .HasForeignKey(d => d.TeacherId)
                    .HasConstraintName("FK__Teacher_E__Teach__00200768");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}