// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Bookware.Models
{
    public partial class BookwareDBContext : DbContext
    {
        public BookwareDBContext()
        {
        }

        public BookwareDBContext(DbContextOptions<BookwareDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassBook> ClassBooks { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EducationSubject> EducationSubjects { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeacherSubject> TeacherSubjects { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Class>(entity =>
            {
                entity.HasOne(d => d.EduSub)
                    .WithMany(p => p.Classes)
                    .HasForeignKey(d => d.EduSubId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Class__EduSub_Id__787EE5A0");

                entity.HasOne(d => d.Student)
                    .WithMany(p => p.Classes)
                    .HasForeignKey(d => d.StudentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Class__Student_I__7A672E12");

                entity.HasOne(d => d.TeacherSub)
                    .WithMany(p => p.Classes)
                    .HasForeignKey(d => d.TeacherSubId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Class__TeacherSu__797309D9");
            });

            modelBuilder.Entity<ClassBook>(entity =>
            {
                entity.HasKey(e => e.CbId)
                    .HasName("PK__Class_Bo__4A5EFCFDE28C79E9");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.ClassBooks)
                    .HasForeignKey(d => d.BookId)
                    .HasConstraintName("FK__Class_Boo__Book___00200768");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.ClassBooks)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__Class_Boo__Class__7F2BE32F");
            });

            modelBuilder.Entity<Education>(entity =>
            {
                entity.HasKey(e => e.EduId)
                    .HasName("PK__Educatio__E5726EA2ABA29282");
            });

            modelBuilder.Entity<EducationSubject>(entity =>
            {
                entity.HasKey(e => e.EduSubId)
                    .HasName("PK__Educatio__6039339DA20D605E");

                entity.HasOne(d => d.Edu)
                    .WithMany(p => p.EducationSubjects)
                    .HasForeignKey(d => d.EduId)
                    .HasConstraintName("FK__Education__Edu_I__72C60C4A");

                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.EducationSubjects)
                    .HasForeignKey(d => d.SubjectId)
                    .HasConstraintName("FK__Education__Subje__73BA3083");
            });

            modelBuilder.Entity<TeacherSubject>(entity =>
            {
                entity.HasKey(e => e.TeacherSubId)
                    .HasName("PK__Teacher___71E30E6C56D3A7CF");

                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.TeacherSubjects)
                    .HasForeignKey(d => d.SubjectId)
                    .HasConstraintName("FK__Teacher_S__Subje__6E01572D");

                entity.HasOne(d => d.Teacher)
                    .WithMany(p => p.TeacherSubjects)
                    .HasForeignKey(d => d.TeacherId)
                    .HasConstraintName("FK__Teacher_S__Teach__6D0D32F4");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}