// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Class_Book")]
    public partial class ClassBook
    {
        [Key]
        [Column("CB_Id")]
        public int CbId { get; set; }
        [Column("Class_Id")]
        public int ClassId { get; set; }
        [Column("Book_Id")]
        public int BookId { get; set; }

        [ForeignKey("BookId")]
        [InverseProperty("ClassBooks")]
        public virtual Book Book { get; set; }
        [ForeignKey("ClassId")]
        [InverseProperty("ClassBooks")]
        public virtual Class Class { get; set; }
    }
}