// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Class")]
    public partial class Class
    {
        public Class()
        {
            ClassBooks = new HashSet<ClassBook>();
            Students = new HashSet<Student>();
            TeacherClasses = new HashSet<TeacherClass>();
        }

        [Key]
        [Column("Class_Id")]
        public int ClassId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ClassName { get; set; }

        [InverseProperty("Class")]
        public virtual ICollection<ClassBook> ClassBooks { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<Student> Students { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<TeacherClass> TeacherClasses { get; set; }
    }
}