// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Education_Subject")]
    public partial class EducationSubject
    {
        public EducationSubject()
        {
            Classes = new HashSet<Class>();
        }

        [Key]
        [Column("EduSub_Id")]
        public int EduSubId { get; set; }
        [Column("Edu_Id")]
        public int EduId { get; set; }
        [Column("Subject_Id")]
        public int SubjectId { get; set; }

        [ForeignKey("EduId")]
        [InverseProperty("EducationSubjects")]
        public virtual Education Edu { get; set; }
        [ForeignKey("SubjectId")]
        [InverseProperty("EducationSubjects")]
        public virtual Subject Subject { get; set; }
        [InverseProperty("EduSub")]
        public virtual ICollection<Class> Classes { get; set; }
    }
}