// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Education")]
    public partial class Education
    {
        public Education()
        {
            EduSubs = new HashSet<EduSub>();
        }

        [Key]
        [Column("Edu_Id")]
        public int EduId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string EduName { get; set; }

        [InverseProperty("Edu")]
        public virtual ICollection<EduSub> EduSubs { get; set; }
    }
}