// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Subject")]
    public partial class Subject
    {
        public Subject()
        {
            EducationSubjects = new HashSet<EducationSubject>();
            TeacherSubjects = new HashSet<TeacherSubject>();
        }

        [Key]
        [Column("Subject_Id")]
        public int SubjectId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string SubjectName { get; set; }

        [InverseProperty("Subject")]
        public virtual ICollection<EducationSubject> EducationSubjects { get; set; }
        [InverseProperty("Subject")]
        public virtual ICollection<TeacherSubject> TeacherSubjects { get; set; }
    }
}