// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Teacher_Edu")]
    public partial class TeacherEdu
    {
        public TeacherEdu()
        {
            TeacherClasses = new HashSet<TeacherClass>();
        }

        [Key]
        [Column("TeachEdu_Id")]
        public int TeachEduId { get; set; }
        [Column("Teacher_Id")]
        public int TeacherId { get; set; }
        [Column("EduSub_Id")]
        public int EduSubId { get; set; }

        [ForeignKey("EduSubId")]
        [InverseProperty("TeacherEdus")]
        public virtual EduSub EduSub { get; set; }
        [ForeignKey("TeacherId")]
        [InverseProperty("TeacherEdus")]
        public virtual Teacher Teacher { get; set; }
        [InverseProperty("TeachEdu")]
        public virtual ICollection<TeacherClass> TeacherClasses { get; set; }
    }
}