// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Teacher")]
    public partial class Teacher
    {
        public Teacher()
        {
            TeacherEdus = new HashSet<TeacherEdu>();
        }

        [Key]
        [Column("Teacher_Id")]
        public int TeacherId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("Teacher")]
        public virtual ICollection<TeacherEdu> TeacherEdus { get; set; }
    }
}