// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Teacher_Class")]
    public partial class TeacherClass
    {
        [Key]
        [Column("TeachClass_Id")]
        public int TeachClassId { get; set; }
        [Column("Class_Id")]
        public int ClassId { get; set; }
        [Column("TeachEdu_Id")]
        public int TeachEduId { get; set; }

        [ForeignKey("ClassId")]
        [InverseProperty("TeacherClasses")]
        public virtual Class Class { get; set; }
        [ForeignKey("TeachEduId")]
        [InverseProperty("TeacherClasses")]
        public virtual TeacherEdu TeachEdu { get; set; }
    }
}