// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookware.Models
{
    [Table("Teacher_Subject")]
    public partial class TeacherSubject
    {
        public TeacherSubject()
        {
            Classes = new HashSet<Class>();
        }

        [Key]
        [Column("TeacherSub_Id")]
        public int TeacherSubId { get; set; }
        [Column("Teacher_Id")]
        public int TeacherId { get; set; }
        [Column("Subject_Id")]
        public int SubjectId { get; set; }

        [ForeignKey("SubjectId")]
        [InverseProperty("TeacherSubjects")]
        public virtual Subject Subject { get; set; }
        [ForeignKey("TeacherId")]
        [InverseProperty("TeacherSubjects")]
        public virtual Teacher Teacher { get; set; }
        [InverseProperty("TeacherSub")]
        public virtual ICollection<Class> Classes { get; set; }
    }
}